# Generated by Django 2.0 on 2019-01-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='range',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
