# Generated by Django 2.0 on 2019-01-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_questionoption_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='image_header',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='tally_type',
            field=models.TextField(blank=True, choices=[('SAINTELAGUE', 'SAINTELAGUE'), ('DHONDT', 'PDHONDT'), ('NMAJORREST', 'MAJORREST'), ('SAINTELAGUEMOD', 'SAINTELAGUEMOD')], null=True),
        ),
    ]
