# Generated by Django 2.0 on 2018-12-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='custom_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
