# Generated by Django 2.0 on 2018-12-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_custom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='public_voting',
            field=models.BooleanField(default=False),
        ),
    ]
