# Generated by Django 2.0 on 2018-12-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20181208_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='custom_url',
        ),
    ]
