# Generated by Django 2.0 on 2018-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_voting_custom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='custom_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
