# Generated by Django 2.0 on 2018-12-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20181228_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='question',
            field=models.ManyToManyField(related_name='voting_questions', to='voting.Question'),
        ),
    ]
