# Generated by Django 2.0 on 2019-01-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20181210_1127'),
        ('voting', '0007_auto_20181228_1116'),
        ('voting', '0007_voting_custom_url'),
    ]

    operations = [
    ]
