# Generated by Django 2.0 on 2019-01-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

   dependencies = [
       ('voting', '0010_auto_20190108_1901'),
   ]

   operations = [
       migrations.RemoveField(
           model_name='questionoption',
           name='type',
       ),
       migrations.AddField(
           model_name='question',
           name='type',
           field=models.TextField(blank=True, choices=[('Range', 'Range'), ('Percentage', 'Percentage'), ('Normal', 'Normal')], null=True),
       ),
   ]