# Generated by Django 2.0 on 2019-01-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20190110_1645'),
        ('voting', '0011_auto_20190110_1641'),
    ]

    operations = [
    ]
